"""add password

Revision ID: 578150ae72c8
Revises: a4ddb77c0941
Create Date: 2017-02-07 19:02:35.725606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578150ae72c8'
down_revision = 'a4ddb77c0941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
